name: Deploy Frontend to S3 (Dynamic API + Secure Bucket)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download API URL artifact from backend
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: deploy-backend.yml
          name: api-url
          repo: hybridmulticloud/resume-api-backend
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download CloudFront ID artifact from backend
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: deploy-backend.yml
          name: cloudfront-id
          repo: hybridmulticloud/resume-api-backend
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Inject API Gateway URL into index.html
        run: sed -i "s|API_PLACEHOLDER|$(cat api_url.txt)|" public/index.html

      - name: Read and export CloudFront ID
        run: echo "CLOUDFRONT_ID=$(cat cloudfront_id.txt)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if S3 bucket exists
        run: aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET_NAME }}

      - name: Upload frontend files to S3
        run: |
          aws s3 sync public/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --cache-control "no-store"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_ID" \
            --paths "/*"
