name: Deploy Frontend to S3 (Dynamic API + Secure Bucket)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend   # assumes you run backend in the same pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-url
          path: infra-artifacts

      - name: Download CloudFront ID artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudfront-id
          path: infra-artifacts

      - name: Build index.html from template
        run: |
          export API_URL="$(cat infra-artifacts/api-url.txt)"
          envsubst < public/index.tmpl.html > public/index.html

      - name: Export CloudFront distribution ID
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=$(cat infra-artifacts/cloudfront-id.txt)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Verify S3 bucket exists
        run: aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET_NAME }}

      - name: Sync public/ to S3
        uses: aws-actions/s3-sync@v1
        with:
          bucket:     ${{ secrets.S3_BUCKET_NAME }}
          source-dir: public/
          delete:     true
          cache-control: |
            index.html: max-age=0,no-cache,no-store,must-revalidate
            *.css:      max-age=86400
            *.js:       max-age=86400

      - name: Invalidate CloudFront cache
        uses: aws-actions/cloudfront-invalidate@v1
        with:
          distribution-id:    ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation-paths: |
            /index.html
            /*.css
            /*.js
