name: Deploy Frontend to S3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download API URL artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: deploy-backend.yml
          name: api-url
          repo: hybridmulticloud/resume-api-backend
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download CloudFront ID artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: deploy-backend.yml
          name: cloudfront-id
          repo: hybridmulticloud/resume-api-backend
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Inject API into HTML
        run: sed -i "s|API_PLACEHOLDER|$(cat api_url.txt)|" public/index.html

      - name: Export CloudFront ID
        run: echo "CLOUDFRONT_ID=$(cat cloudfront_id.txt)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync public/ s3://hybridmulti.cloud --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_ID" \
            --paths "/*"
